// @generated by iso20022-reference-gen; do not edit.

pub const REFERENCE_DATA_MANIFEST_SHA256: &str =
    "c7b81295e55db391279fca9a500c1bd2efdbdd31ef861bf2beeeec78d52260c1";

#[derive(Debug, Clone, Copy)]
pub(crate) struct IbanFormat {
    pub country: &'static str,
    pub total_length: u8,
    pub bban_pattern: &'static str,
}

pub(crate) const IBAN_FORMATS: &[IbanFormat] = &[
    IbanFormat {
        country: "AD",
        total_length: 24,
        bban_pattern: "nnnnnnnncccccccccccc",
    },
    IbanFormat {
        country: "AE",
        total_length: 23,
        bban_pattern: "nnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "AL",
        total_length: 28,
        bban_pattern: "nnnnnnnncccccccccccccccc",
    },
    IbanFormat {
        country: "AT",
        total_length: 20,
        bban_pattern: "nnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "AZ",
        total_length: 28,
        bban_pattern: "aaaacccccccccccccccccccc",
    },
    IbanFormat {
        country: "BA",
        total_length: 20,
        bban_pattern: "nnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "BE",
        total_length: 16,
        bban_pattern: "nnnnnnnnnnnn",
    },
    IbanFormat {
        country: "BG",
        total_length: 22,
        bban_pattern: "aaaannnnnncccccccc",
    },
    IbanFormat {
        country: "BH",
        total_length: 22,
        bban_pattern: "aaaacccccccccccccc",
    },
    IbanFormat {
        country: "BI",
        total_length: 27,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "BR",
        total_length: 29,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnnnnac",
    },
    IbanFormat {
        country: "BY",
        total_length: 28,
        bban_pattern: "ccccnnnncccccccccccccccc",
    },
    IbanFormat {
        country: "CH",
        total_length: 21,
        bban_pattern: "nnnnncccccccccccc",
    },
    IbanFormat {
        country: "CR",
        total_length: 22,
        bban_pattern: "nnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "CY",
        total_length: 28,
        bban_pattern: "nnnnnnnncccccccccccccccc",
    },
    IbanFormat {
        country: "CZ",
        total_length: 24,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "DE",
        total_length: 22,
        bban_pattern: "nnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "DJ",
        total_length: 27,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "DK",
        total_length: 18,
        bban_pattern: "nnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "DO",
        total_length: 28,
        bban_pattern: "ccccnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "EE",
        total_length: 20,
        bban_pattern: "nnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "EG",
        total_length: 29,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "ES",
        total_length: 24,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "FI",
        total_length: 18,
        bban_pattern: "nnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "FK",
        total_length: 18,
        bban_pattern: "aannnnnnnnnnnn",
    },
    IbanFormat {
        country: "FO",
        total_length: 18,
        bban_pattern: "nnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "FR",
        total_length: 27,
        bban_pattern: "nnnnnnnnnncccccccccccnn",
    },
    IbanFormat {
        country: "GB",
        total_length: 22,
        bban_pattern: "aaaannnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "GE",
        total_length: 22,
        bban_pattern: "aannnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "GI",
        total_length: 23,
        bban_pattern: "aaaaccccccccccccccc",
    },
    IbanFormat {
        country: "GL",
        total_length: 18,
        bban_pattern: "nnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "GR",
        total_length: 27,
        bban_pattern: "nnnnnnncccccccccccccccc",
    },
    IbanFormat {
        country: "GT",
        total_length: 28,
        bban_pattern: "cccccccccccccccccccccccc",
    },
    IbanFormat {
        country: "HN",
        total_length: 28,
        bban_pattern: "aaaannnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "HR",
        total_length: 21,
        bban_pattern: "nnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "HU",
        total_length: 28,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "IE",
        total_length: 22,
        bban_pattern: "aaaannnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "IL",
        total_length: 23,
        bban_pattern: "nnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "IQ",
        total_length: 23,
        bban_pattern: "aaaannnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "IS",
        total_length: 26,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "IT",
        total_length: 27,
        bban_pattern: "annnnnnnnnncccccccccccc",
    },
    IbanFormat {
        country: "JO",
        total_length: 30,
        bban_pattern: "aaaannnncccccccccccccccccc",
    },
    IbanFormat {
        country: "KW",
        total_length: 30,
        bban_pattern: "aaaacccccccccccccccccccccc",
    },
    IbanFormat {
        country: "KZ",
        total_length: 20,
        bban_pattern: "nnnccccccccccccc",
    },
    IbanFormat {
        country: "LB",
        total_length: 28,
        bban_pattern: "nnnncccccccccccccccccccc",
    },
    IbanFormat {
        country: "LC",
        total_length: 32,
        bban_pattern: "aaaacccccccccccccccccccccccc",
    },
    IbanFormat {
        country: "LI",
        total_length: 21,
        bban_pattern: "nnnnncccccccccccc",
    },
    IbanFormat {
        country: "LT",
        total_length: 20,
        bban_pattern: "nnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "LU",
        total_length: 20,
        bban_pattern: "nnnccccccccccccc",
    },
    IbanFormat {
        country: "LV",
        total_length: 21,
        bban_pattern: "aaaaccccccccccccc",
    },
    IbanFormat {
        country: "LY",
        total_length: 25,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "MC",
        total_length: 27,
        bban_pattern: "nnnnnnnnnncccccccccccnn",
    },
    IbanFormat {
        country: "MD",
        total_length: 24,
        bban_pattern: "cccccccccccccccccccc",
    },
    IbanFormat {
        country: "ME",
        total_length: 22,
        bban_pattern: "nnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "MK",
        total_length: 19,
        bban_pattern: "nnnccccccccccnn",
    },
    IbanFormat {
        country: "MN",
        total_length: 20,
        bban_pattern: "nnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "MR",
        total_length: 27,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "MT",
        total_length: 31,
        bban_pattern: "aaaannnnncccccccccccccccccc",
    },
    IbanFormat {
        country: "MU",
        total_length: 30,
        bban_pattern: "aaaannnnnnnnnnnnnnnnnnnaaa",
    },
    IbanFormat {
        country: "NI",
        total_length: 28,
        bban_pattern: "aaaannnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "NL",
        total_length: 18,
        bban_pattern: "aaaannnnnnnnnn",
    },
    IbanFormat {
        country: "NO",
        total_length: 15,
        bban_pattern: "nnnnnnnnnnn",
    },
    IbanFormat {
        country: "OM",
        total_length: 23,
        bban_pattern: "nnncccccccccccccccc",
    },
    IbanFormat {
        country: "PK",
        total_length: 24,
        bban_pattern: "aaaacccccccccccccccc",
    },
    IbanFormat {
        country: "PL",
        total_length: 28,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "PS",
        total_length: 29,
        bban_pattern: "aaaaccccccccccccccccccccc",
    },
    IbanFormat {
        country: "PT",
        total_length: 25,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "QA",
        total_length: 29,
        bban_pattern: "aaaaccccccccccccccccccccc",
    },
    IbanFormat {
        country: "RO",
        total_length: 24,
        bban_pattern: "aaaacccccccccccccccc",
    },
    IbanFormat {
        country: "RS",
        total_length: 22,
        bban_pattern: "nnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "RU",
        total_length: 33,
        bban_pattern: "nnnnnnnnnnnnnnccccccccccccccc",
    },
    IbanFormat {
        country: "SA",
        total_length: 24,
        bban_pattern: "nncccccccccccccccccc",
    },
    IbanFormat {
        country: "SC",
        total_length: 31,
        bban_pattern: "aaaannnnnnnnnnnnnnnnnnnnaaa",
    },
    IbanFormat {
        country: "SD",
        total_length: 18,
        bban_pattern: "nnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "SE",
        total_length: 24,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "SI",
        total_length: 19,
        bban_pattern: "nnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "SK",
        total_length: 24,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "SM",
        total_length: 27,
        bban_pattern: "annnnnnnnnncccccccccccc",
    },
    IbanFormat {
        country: "SO",
        total_length: 23,
        bban_pattern: "nnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "ST",
        total_length: 25,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "SV",
        total_length: 28,
        bban_pattern: "aaaannnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "TL",
        total_length: 23,
        bban_pattern: "nnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "TN",
        total_length: 24,
        bban_pattern: "nnnnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "TR",
        total_length: 26,
        bban_pattern: "nnnnnncccccccccccccccc",
    },
    IbanFormat {
        country: "UA",
        total_length: 29,
        bban_pattern: "nnnnnnccccccccccccccccccc",
    },
    IbanFormat {
        country: "VA",
        total_length: 22,
        bban_pattern: "nnnnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "VG",
        total_length: 24,
        bban_pattern: "aaaannnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "XK",
        total_length: 20,
        bban_pattern: "nnnnnnnnnnnnnnnn",
    },
    IbanFormat {
        country: "YE",
        total_length: 30,
        bban_pattern: "aaaannnncccccccccccccccccc",
    },
];

#[derive(Debug, Clone, Copy)]
pub(crate) struct CurrencyRecord {
    pub code: &'static str,
    pub minor_units: Option<u8>,
}

pub(crate) const CURRENCIES: &[CurrencyRecord] = &[
    CurrencyRecord {
        code: "AED",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "AFN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ALL",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "AMD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "AOA",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ARS",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "AUD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "AWG",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "AZN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BAM",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BBD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BDT",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BHD",
        minor_units: Some(3),
    },
    CurrencyRecord {
        code: "BIF",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "BMD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BND",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BOB",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BOV",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BRL",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BSD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BTN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BWP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BYN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "BZD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CAD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CDF",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CHE",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CHF",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CHW",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CLF",
        minor_units: Some(4),
    },
    CurrencyRecord {
        code: "CLP",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "CNY",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "COP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "COU",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CRC",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CUP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CVE",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "CZK",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "DJF",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "DKK",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "DOP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "DZD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "EGP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ERN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ETB",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "EUR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "FJD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "FKP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "GBP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "GEL",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "GHS",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "GIP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "GMD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "GNF",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "GTQ",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "GYD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "HKD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "HNL",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "HTG",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "HUF",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "IDR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ILS",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "INR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "IQD",
        minor_units: Some(3),
    },
    CurrencyRecord {
        code: "IRR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ISK",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "JMD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "JOD",
        minor_units: Some(3),
    },
    CurrencyRecord {
        code: "JPY",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "KES",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "KGS",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "KHR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "KMF",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "KPW",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "KRW",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "KWD",
        minor_units: Some(3),
    },
    CurrencyRecord {
        code: "KYD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "KZT",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "LAK",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "LBP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "LKR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "LRD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "LSL",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "LYD",
        minor_units: Some(3),
    },
    CurrencyRecord {
        code: "MAD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MDL",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MGA",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MKD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MMK",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MNT",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MOP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MRU",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MUR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MVR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MWK",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MXN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MXV",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MYR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "MZN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "NAD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "NGN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "NIO",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "NOK",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "NPR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "NZD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "OMR",
        minor_units: Some(3),
    },
    CurrencyRecord {
        code: "PAB",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "PEN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "PGK",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "PHP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "PKR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "PLN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "PYG",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "QAR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "RON",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "RSD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "RUB",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "RWF",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "SAR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SBD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SCR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SDG",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SEK",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SGD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SHP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SLE",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SOS",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SRD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SSP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "STN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SVC",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SYP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "SZL",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "THB",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "TJS",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "TMT",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "TND",
        minor_units: Some(3),
    },
    CurrencyRecord {
        code: "TOP",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "TRY",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "TTD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "TWD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "TZS",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "UAH",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "UGX",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "USD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "USN",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "UYI",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "UYU",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "UYW",
        minor_units: Some(4),
    },
    CurrencyRecord {
        code: "UZS",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "VED",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "VES",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "VND",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "VUV",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "WST",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "XAD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "XAF",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "XAG",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XAU",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XBA",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XBB",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XBC",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XBD",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XCD",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "XCG",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "XDR",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XOF",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "XPD",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XPF",
        minor_units: Some(0),
    },
    CurrencyRecord {
        code: "XPT",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XSU",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XTS",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XUA",
        minor_units: None,
    },
    CurrencyRecord {
        code: "XXX",
        minor_units: None,
    },
    CurrencyRecord {
        code: "YER",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ZAR",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ZMW",
        minor_units: Some(2),
    },
    CurrencyRecord {
        code: "ZWG",
        minor_units: Some(2),
    },
];

#[rustfmt::skip]
pub(crate) const COUNTRY_CODES: &[&str] = &[
    "AD",
    "AE",
    "AF",
    "AG",
    "AI",
    "AL",
    "AM",
    "AO",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AW",
    "AX",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BL",
    "BM",
    "BN",
    "BO",
    "BQ",
    "BR",
    "BS",
    "BT",
    "BV",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CC",
    "CD",
    "CF",
    "CG",
    "CH",
    "CI",
    "CK",
    "CL",
    "CM",
    "CN",
    "CO",
    "CR",
    "CU",
    "CV",
    "CW",
    "CX",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "EH",
    "ER",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FK",
    "FM",
    "FO",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GF",
    "GG",
    "GH",
    "GI",
    "GL",
    "GM",
    "GN",
    "GP",
    "GQ",
    "GR",
    "GS",
    "GT",
    "GU",
    "GW",
    "GY",
    "HK",
    "HM",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IM",
    "IN",
    "IO",
    "IQ",
    "IR",
    "IS",
    "IT",
    "JE",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KP",
    "KR",
    "KW",
    "KY",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MF",
    "MG",
    "MH",
    "MK",
    "ML",
    "MM",
    "MN",
    "MO",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NC",
    "NE",
    "NF",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NU",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PF",
    "PG",
    "PH",
    "PK",
    "PL",
    "PM",
    "PN",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RE",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SD",
    "SE",
    "SG",
    "SH",
    "SI",
    "SJ",
    "SK",
    "SL",
    "SM",
    "SN",
    "SO",
    "SR",
    "SS",
    "ST",
    "SV",
    "SX",
    "SY",
    "SZ",
    "TC",
    "TD",
    "TF",
    "TG",
    "TH",
    "TJ",
    "TK",
    "TL",
    "TM",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UM",
    "US",
    "UY",
    "UZ",
    "VA",
    "VC",
    "VE",
    "VG",
    "VI",
    "VN",
    "VU",
    "WF",
    "WS",
    "YE",
    "YT",
    "ZA",
    "ZM",
    "ZW",
];
