use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use crate::descriptor::SchemaDescriptor;

const GENERATED_HEADER: &str = "// @generated by rust_iso20022_codegen 0.1.0; do not edit.\n// schema set: xsds/schema-set.json; schema manifest: xsds/schema-manifest.json\n// generator config: tools/codegen/generator-config.toml; generator manifest: tools/codegen/generator-manifest.json\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CoverageError {
    DuplicateDescriptor {
        identity: String,
    },
    MissingDescriptor {
        identity: String,
    },
    UnexpectedDescriptor {
        identity: String,
    },
    GeneratedModuleMismatch {
        identity: String,
        expected: String,
        actual: String,
    },
}

pub fn verify_release_coverage(
    descriptors: &[SchemaDescriptor],
    expected: &[(String, String)],
) -> Result<(), CoverageError> {
    let mut actual = BTreeMap::new();
    for descriptor in descriptors {
        if actual
            .insert(
                descriptor.identity.clone(),
                descriptor.generated_module.clone(),
            )
            .is_some()
        {
            return Err(CoverageError::DuplicateDescriptor {
                identity: descriptor.identity.clone(),
            });
        }
    }
    let expected_map: BTreeMap<_, _> = expected.iter().cloned().collect();
    for (identity, module) in &expected_map {
        let Some(actual_module) = actual.get(identity) else {
            return Err(CoverageError::MissingDescriptor {
                identity: identity.clone(),
            });
        };
        if actual_module != module {
            return Err(CoverageError::GeneratedModuleMismatch {
                identity: identity.clone(),
                expected: module.clone(),
                actual: actual_module.clone(),
            });
        }
    }
    if let Some(identity) = actual
        .keys()
        .find(|identity| !expected_map.contains_key(*identity))
    {
        return Err(CoverageError::UnexpectedDescriptor {
            identity: identity.clone(),
        });
    }
    Ok(())
}

pub fn write_legacy(path: &Path, descriptors: &[SchemaDescriptor]) -> Result<(), String> {
    let mut sorted = descriptors.to_vec();
    sorted.sort_by(|left, right| left.identity.cmp(&right.identity));
    let mut output = String::from(GENERATED_HEADER);
    output.push_str("use super::CatalogueEntry;\nuse phf::phf_map;\n\n");
    output.push_str("pub static ENTRIES: &[CatalogueEntry] = &[\n");
    for descriptor in &sorted {
        let name = &descriptor.identity;
        let namespace = &descriptor.namespace;
        let area = &descriptor.business_area;
        output.push_str(&format!(
            "    CatalogueEntry {{ message_name: {name:?}, namespace: {namespace:?}, business_area: {area:?}, has_model: true }},\n"
        ));
    }
    output.push_str(
        "];\n\npub static BY_NAME: phf::Map<&'static str, CatalogueEntry> = phf_map! {\n",
    );
    for descriptor in &sorted {
        let name = &descriptor.identity;
        let namespace = &descriptor.namespace;
        let area = &descriptor.business_area;
        output.push_str(&format!(
            "    {name:?} => CatalogueEntry {{ message_name: {name:?}, namespace: {namespace:?}, business_area: {area:?}, has_model: true }},\n"
        ));
    }
    output.push_str("};\n");
    fs::write(path, output).map_err(|error| format!("write {}: {error}", path.display()))
}

pub fn write_indices(path: &Path, descriptors: &[SchemaDescriptor]) -> Result<(), String> {
    let mut sorted = descriptors.to_vec();
    sorted.sort_by_key(descriptor_sort_key);
    let mut identities = BTreeSet::new();
    let mut namespaces = BTreeSet::new();
    let mut roots = BTreeSet::new();
    let mut families: BTreeMap<String, (usize, usize)> = BTreeMap::new();
    for (ordinal, descriptor) in sorted.iter().enumerate() {
        if !identities.insert(descriptor.identity.clone()) {
            return Err(format!(
                "duplicate descriptor identity {}",
                descriptor.identity
            ));
        }
        if !namespaces.insert(descriptor.namespace.clone()) {
            return Err(format!(
                "duplicate descriptor namespace {}",
                descriptor.namespace
            ));
        }
        let root_key = format!("{}\u{1f}{}", descriptor.namespace, descriptor.root_element);
        if !roots.insert(root_key) {
            return Err(format!(
                "duplicate descriptor namespace/root {}",
                descriptor.identity
            ));
        }
        let family = family_of(&descriptor.identity)?;
        families
            .entry(family)
            .and_modify(|range| range.1 += 1)
            .or_insert((ordinal, 1));
    }

    let mut output = String::from(GENERATED_HEADER);
    output.push_str("use phf::phf_map;\n\n");
    output.push_str(&format!(
        "pub const DESCRIPTOR_COUNT: usize = {};\n\n",
        sorted.len()
    ));
    output.push_str("pub static BY_ID: phf::Map<&'static str, usize> = phf_map! {\n");
    for (ordinal, descriptor) in sorted.iter().enumerate() {
        output.push_str(&format!(
            "    {:?} => {ordinal}usize,\n",
            descriptor.identity
        ));
    }
    output.push_str("};\n\npub static BY_NAMESPACE: phf::Map<&'static str, usize> = phf_map! {\n");
    for (ordinal, descriptor) in sorted.iter().enumerate() {
        output.push_str(&format!(
            "    {:?} => {ordinal}usize,\n",
            descriptor.namespace
        ));
    }
    output.push_str("};\n\npub static BY_ROOT: phf::Map<&'static str, usize> = phf_map! {\n");
    for (ordinal, descriptor) in sorted.iter().enumerate() {
        let key = format!("{}\u{1f}{}", descriptor.namespace, descriptor.root_element);
        output.push_str(&format!("    {key:?} => {ordinal}usize,\n"));
    }
    output.push_str(
        "};\n\npub static FAMILY_RANGES: phf::Map<&'static str, (usize, usize)> = phf_map! {\n",
    );
    for (family, (start, length)) in families {
        output.push_str(&format!(
            "    {family:?} => ({start}usize, {length}usize),\n"
        ));
    }
    output.push_str("};\n");
    fs::write(path, output).map_err(|error| format!("write {}: {error}", path.display()))
}

fn descriptor_sort_key(descriptor: &SchemaDescriptor) -> (String, u32, String) {
    let family = family_of(&descriptor.identity).unwrap_or_default();
    let version = descriptor
        .identity
        .rsplit('.')
        .next()
        .and_then(|value| value.parse().ok())
        .unwrap_or(0);
    (family, version, descriptor.identity.clone())
}

fn family_of(identity: &str) -> Result<String, String> {
    let mut parts = identity.split('.');
    let area = parts
        .next()
        .ok_or_else(|| format!("invalid identity {identity}"))?;
    let functionality = parts
        .next()
        .ok_or_else(|| format!("invalid identity {identity}"))?;
    let variant = parts
        .next()
        .ok_or_else(|| format!("invalid identity {identity}"))?;
    let version = parts
        .next()
        .ok_or_else(|| format!("invalid identity {identity}"))?;
    if parts.next().is_some() || version.is_empty() {
        return Err(format!("invalid identity {identity}"));
    }
    Ok(format!("{area}.{functionality}.{variant}"))
}
