//! XSD -> yaserde Rust code generator for rust_iso20022.
//!
//! Drives `xsd-parser` to turn each ISO 20022 message schema in `xsds/` into a
//! Rust module under `src/generated/<family>/<message>.rs`, with the import
//! header the generated code needs and the local `Validate` impls.
//!
//! Build/run with the `codegen` feature:
//! ```bash
//! cargo run --features codegen --bin codegen -- --input xsds --output src/generated
//! ```
//!
//! This binary is excluded from the published crate; downstream users only ever
//! see the already-generated `src/generated` tree.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use xsd_parser::generator::builder::GeneratorBuilder;
use xsd_parser::parser::parse;

const HEADER: &str = "\
// @generated by src/bin/codegen.rs from the ISO 20022 XSD schema. Do not edit.
#![allow(clippy::all)]
#![allow(non_snake_case, non_camel_case_types, dead_code, unused_imports)]
// yaserde_derive 0.7 emits trait impls inside nested choice submodules, which
// trips the `non_local_definitions` lint on recent rustc. The generated code is
// correct; silence the lint here.
#![allow(non_local_definitions)]
use std::str::FromStr;
use crate::validate::Validate;
use yaserde_derive::{YaDeserialize, YaSerialize};
";

/// Messages excluded from generation. Multiple anonymous `<xsd:choice>` groups
/// (which used to live here) are now handled by `disambiguate_inline_choices`,
/// so this is empty — all 502 staged schemas generate a model.
const SKIP: &[&str] = &[];

struct Args {
    input: PathBuf,
    output: PathBuf,
    /// When non-empty, only generate these basenames (e.g. "pacs.008.001.08.xsd").
    /// `--only` may be repeated to generate a verification subset.
    only: Vec<String>,
    /// Ignore the SKIP list (for working on the unsupported messages).
    no_skip: bool,
}

fn parse_args() -> Args {
    let mut input = PathBuf::from("xsds");
    let mut output = PathBuf::from("src/generated");
    let mut only = Vec::new();
    let mut no_skip = false;
    let mut it = std::env::args().skip(1);
    while let Some(a) = it.next() {
        match a.as_str() {
            "--input" | "-i" => input = PathBuf::from(it.next().expect("--input needs a value")),
            "--output" | "-o" => output = PathBuf::from(it.next().expect("--output needs a value")),
            "--only" => only.push(it.next().expect("--only needs a value")),
            "--no-skip" => no_skip = true,
            other => eprintln!("ignoring unknown arg: {other}"),
        }
    }
    Args { input, output, only, no_skip }
}

/// `pacs.008.001.08.xsd` -> (family `pacs`, stem `pacs_008_001_08`, name
/// `pacs.008.001.08`). Tolerates mirror artifacts like a trailing `_0` on the
/// version (`acmt.017.001.03_0.xsd`), normalising back to the canonical name.
/// Returns `None` for names that are not `aaaa.ddd.ddd.dd`.
fn message_stem(basename: &str) -> Option<(String, String, String)> {
    let name = basename.strip_suffix(".xsd")?;
    let parts: Vec<&str> = name.split('.').collect();
    if parts.len() != 4 {
        return None;
    }
    // Drop any `_suffix` on the version component (mirror duplication artifact).
    let version = parts[3].split('_').next().unwrap_or(parts[3]);
    let canonical_ok = parts[0].len() == 4
        && parts[0].bytes().all(|b| b.is_ascii_lowercase())
        && parts[1].len() == 3
        && parts[2].len() == 3
        && version.len() == 2
        && parts[1..3].iter().all(|p| p.bytes().all(|b| b.is_ascii_digit()))
        && version.bytes().all(|b| b.is_ascii_digit());
    if !canonical_ok {
        return None;
    }
    let family = parts[0].to_string();
    let message_name = format!("{}.{}.{}.{}", parts[0], parts[1], parts[2], version);
    let stem = message_name.replace('.', "_");
    Some((family, stem, message_name))
}

/// Pull `urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08` out of the schema text.
fn extract_namespace(xsd: &str) -> Option<String> {
    let key = "targetNamespace=\"";
    let start = xsd.find(key)? + key.len();
    let end = xsd[start..].find('"')? + start;
    Some(xsd[start..end].to_string())
}

fn generate_one(xsd_text: &str) -> Result<String, String> {
    let rs_file = parse(xsd_text).map_err(|e| format!("parse error: {e:?}"))?;
    let gen = GeneratorBuilder::default().build();
    let body = fix_namespaces(&dedup_items(&gen.generate_rs_file(&rs_file)));
    let body = add_simple_content_values(&body, &simple_content_types(xsd_text));
    let body = disambiguate_inline_choices(&body);
    let body = add_json_support(&body);
    let body = replace_tuple_io(&body);
    Ok(choices_to_fields(&body))
}

/// Rewrite `<xsd:choice>` enums into a struct of `Option<…>` fields (the
/// JAXB/prowide shape). `xsd-parser` models a choice as a `*ChoiceChoice` enum
/// held by a flattened field on a `*Choice` wrapper struct; yaserde then drops a
/// variant's struct attributes on write (so amount `Ccy` is lost) and emits an
/// `<__Unknown__>` placeholder when no variant is set. Representing each variant
/// as an optional element field fixes both: the amount struct serializes as a
/// normal element (attributes included) and an unset choice is simply `None`.
fn choices_to_fields(body: &str) -> String {
    let lines: Vec<&str> = body.lines().collect();
    // 1. Collect each choice enum: name -> Vec<(element_name, field_name, ty, is_vec)>.
    // Only the top-level `*ChoiceChoice` enums whose variants are simple
    // `Variant(Type)` (optionally preceded by yaserde/serde rename attrs) and a
    // trailing `__Unknown__(String)` are handled; anything unexpected is skipped.
    let mut enums: std::collections::HashMap<String, Vec<ChoiceVariant>> = Default::default();
    let mut i = 0;
    while i < lines.len() {
        // Choice enums, top-level or inline (in an indented submodule). Inline
        // disambiguated names carry a suffix (`…Choice2`, `…Choice3`).
        if let Some(rest) = lines[i].trim_start().strip_prefix("pub enum ") {
            let name = rest.trim_end_matches('{').trim().to_string();
            if is_choice_name(&name) {
                if let Some((variants, end)) = parse_choice_enum(&lines, i) {
                    enums.insert(name, variants);
                    i = end;
                    continue;
                }
            }
        }
        i += 1;
    }
    if enums.is_empty() {
        return body.to_string();
    }

    // 2. Emit, dropping enum blocks + their impls, and rewriting wrapper fields.
    let mut out: Vec<String> = Vec::with_capacity(lines.len());
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let t = line.trim_start();

        // Drop the enum block and its `impl Default` / `impl Validate` blocks.
        if let Some(rest) = t.strip_prefix("pub enum ") {
            let name = rest.trim_end_matches('{').trim().to_string();
            if enums.contains_key(&name) {
                i = skip_block(&lines, i); // the enum
                i = skip_following_impls(&lines, i, &name);
                // also drop the preceding derive/attr lines we already emitted
                while out
                    .last()
                    .map(|l| {
                        let lt = l.trim_start();
                        lt.starts_with("#[") || lt.is_empty()
                    })
                    .unwrap_or(false)
                {
                    out.pop();
                }
                continue;
            }
        }

        // Rewrite a wrapper field `pub <snake>: [mod::]<Enum>,` into variant fields.
        if t.starts_with("pub ") && t.ends_with(',') && t.contains(": ") {
            let decl = &t[4..t.len() - 1];
            if let Some((_fname, ty)) = decl.split_once(": ") {
                // The field's enum is the last path segment (`mod::Enum` for
                // inline choices, or a bare `Enum` for top-level ones).
                let key = ty.rsplit("::").next().unwrap_or(ty);
                if let Some(variants) = enums.get(key) {
                    let indent: String =
                        line.chars().take_while(|c| c.is_whitespace()).collect();
                    // Drop the choice field's own attribute lines (`flatten` for
                    // top-level choices, a `rename` for submodule ones); the new
                    // variant fields carry their own attributes.
                    while out
                        .last()
                        .map(|l| l.trim_start().starts_with("#["))
                        .unwrap_or(false)
                    {
                        out.pop();
                    }
                    for v in variants {
                        out.push(format!("{indent}#[yaserde(rename = {:?})]", v.element));
                        out.push(format!(
                            "{indent}#[cfg_attr(feature = \"serde\", serde(rename = {:?}))]",
                            v.element
                        ));
                        let fty = if v.is_vec {
                            v.ty.clone()
                        } else {
                            format!("Option<{}>", v.ty)
                        };
                        out.push(format!("{indent}pub {}: {fty},", v.field));
                    }
                    i += 1;
                    continue;
                }
            }
        }

        out.push(line.to_string());
        i += 1;
    }
    out.join("\n") + "\n"
}

struct ChoiceVariant {
    element: String,
    field: String,
    ty: String,
    is_vec: bool,
}

/// Parse a `pub enum …Choice { … }` starting at `start`. Returns the variants
/// (excluding `__Unknown__`) and the index just past the closing `}`, or `None`
/// if the enum is not the simple single-payload choice shape.
fn parse_choice_enum(lines: &[&str], start: usize) -> Option<(Vec<ChoiceVariant>, usize)> {
    let mut variants = Vec::new();
    let mut pending_rename: Option<String> = None;
    let mut i = start + 1;
    while i < lines.len() {
        let t = lines[i].trim();
        if t == "}" {
            return Some((variants, i + 1));
        }
        if t.is_empty() || t.starts_with("//") {
            i += 1;
            continue;
        }
        if let Some(r) = t.strip_prefix("#[yaserde(rename = \"") {
            pending_rename = r.split('"').next().map(|s| s.to_string());
            i += 1;
            continue;
        }
        if t.starts_with("#[") {
            i += 1;
            continue;
        }
        if t.starts_with("__Unknown__") {
            pending_rename = None;
            i += 1;
            continue;
        }
        // A variant: `Ident(Type),`
        let v = t.trim_end_matches(',');
        let (ident, payload) = v.split_once('(')?;
        let payload = payload.strip_suffix(')')?;
        // Only simple payloads (no nested generics other than a single Vec<…>).
        let is_vec = payload.starts_with("Vec<");
        let ty = payload.to_string();
        if ty.contains(',') {
            return None; // tuple variant — unsupported shape
        }
        let element = pending_rename.take().unwrap_or_else(|| ident.to_string());
        variants.push(ChoiceVariant {
            field: to_snake(ident),
            element,
            ty,
            is_vec,
        });
        i += 1;
    }
    None
}

/// Skip a `{ … }` block starting at `start` (its line opens the block); returns
/// the index just past the matching `}`.
fn skip_block(lines: &[&str], start: usize) -> usize {
    let mut depth = 0i32;
    let mut i = start;
    loop {
        if i >= lines.len() {
            return i;
        }
        depth += lines[i].matches('{').count() as i32 - lines[i].matches('}').count() as i32;
        i += 1;
        if depth <= 0 && i > start {
            return i;
        }
    }
}

/// Skip blank lines and `impl Default for <name>` / `impl Validate for <name>`
/// blocks immediately following a dropped enum.
fn skip_following_impls(lines: &[&str], mut i: usize, name: &str) -> usize {
    loop {
        while i < lines.len() && lines[i].trim().is_empty() {
            i += 1;
        }
        if i < lines.len() {
            let t = lines[i].trim_start();
            if t.starts_with(&format!("impl Default for {name} "))
                || t.starts_with(&format!("impl Validate for {name} "))
                || t.starts_with(&format!("impl Default for {name}{{"))
            {
                i = skip_block(lines, i);
                continue;
            }
        }
        return i;
    }
}

/// Whether an enum name is a choice wrapper (`…Choice`, or a disambiguated
/// `…Choice2` / `…Choice3` from an inline choice).
fn is_choice_name(name: &str) -> bool {
    name.trim_end_matches(|c: char| c.is_ascii_digit())
        .ends_with("Choice")
}

/// PascalCase identifier to snake_case (`InstdAmt` -> `instd_amt`).
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if c.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// Replace the `UtilsTupleIo` / `UtilsDefaultSerde` derives (from the
/// unpublished `xsd-macro-utils`) on leaf newtypes with a call to the local
/// `crate::simple_type!` macro, so the crate depends only on published crates.
fn replace_tuple_io(body: &str) -> String {
    let mut out = String::with_capacity(body.len());
    let mut pending = false;
    for line in body.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("#[derive(") && trimmed.contains("UtilsTupleIo") {
            let cleaned = line
                .replace(", UtilsTupleIo", "")
                .replace(", UtilsDefaultSerde", "")
                .replace("UtilsTupleIo, ", "")
                .replace("UtilsDefaultSerde, ", "")
                .replace("UtilsTupleIo", "")
                .replace("UtilsDefaultSerde", "");
            out.push_str(&cleaned);
            out.push('\n');
            pending = true;
            continue;
        }
        out.push_str(line);
        out.push('\n');
        if pending && trimmed.starts_with("pub struct ") {
            if let Some(rest) = trimmed.strip_prefix("pub struct ") {
                let name = rest
                    .split(|c: char| c == ' ' || c == '(')
                    .next()
                    .unwrap_or("")
                    .trim();
                if !name.is_empty() {
                    out.push_str(&format!("crate::simple_type!({name});\n"));
                }
            }
            pending = false;
        }
    }
    out
}

/// Make the generated types JSON-capable (`serde` feature) and consistent:
///
/// * `xsd-types` scalars (`xs::Decimal`, `xs::Date`, …) have no `serde` impls,
///   so map them to lossless `String` — the same choice already used for
///   monetary amounts (exact text, no float rounding), and yaserde-compatible.
/// * add a feature-gated `serde::{Serialize, Deserialize}` derive next to every
///   yaserde / tuple-io derive, so messages convert to and from JSON.
fn add_json_support(body: &str) -> String {
    let mut out = String::with_capacity(body.len() + body.len() / 8);
    for line in body.lines() {
        let stringified = stringify_xs(line);
        let trimmed = stringified.trim_start();
        if trimmed.starts_with("#[derive(")
            && (trimmed.contains("YaSerialize")
                || trimmed.contains("UtilsTupleIo")
                || trimmed.contains("UtilsDefaultSerde"))
        {
            let indent: String = stringified
                .chars()
                .take_while(|c| c.is_whitespace())
                .collect();
            out.push_str(&indent);
            out.push_str(
                "#[cfg_attr(feature = \"serde\", derive(serde::Serialize, serde::Deserialize))]\n",
            );
        }
        out.push_str(&stringified);
        out.push('\n');

        // Mirror yaserde field/variant attributes onto serde so JSON keys use the
        // ISO 20022 short names (e.g. "MsgId", "IBAN") instead of Rust snake_case.
        if trimmed.starts_with("#[yaserde(") {
            let indent: String = stringified
                .chars()
                .take_while(|c| c.is_whitespace())
                .collect();
            if let Some(name) = extract_attr(trimmed, "rename = \"") {
                out.push_str(&format!(
                    "{indent}#[cfg_attr(feature = \"serde\", serde(rename = {name:?}))]\n"
                ));
            } else if trimmed.contains("flatten") {
                out.push_str(&format!(
                    "{indent}#[cfg_attr(feature = \"serde\", serde(flatten))]\n"
                ));
            }
        }
    }
    out
}

/// Extract a `key"value"` attribute value, e.g. the `rename = "MsgId"` target.
fn extract_attr<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let start = line.find(key)? + key.len();
    let end = line[start..].find('"')? + start;
    Some(&line[start..end])
}

/// Replace `xs::<Ident>` occurrences with `String`.
fn stringify_xs(line: &str) -> String {
    let mut result = String::with_capacity(line.len());
    let mut rest = line;
    while let Some(pos) = rest.find("xs::") {
        result.push_str(&rest[..pos]);
        let after = &rest[pos + 4..];
        let end = after
            .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
            .unwrap_or(after.len());
        result.push_str("String");
        rest = &after[end..];
    }
    result.push_str(rest);
    result
}

/// A complexType with several inline `<xs:choice>` groups makes `xsd-parser`
/// emit a struct with N identically-named fields and a submodule with N
/// identically-named `pub enum`s — which does not compile. We suffix the 2nd…Nth
/// of each (`…Choice2`, `…Choice3`; field `_2`, `_3`) and mark every such field
/// `flatten`, since the choice variants map directly to child elements.
fn disambiguate_inline_choices(body: &str) -> String {
    // Only act when an enum name is actually defined more than once (the real
    // collision). This makes the transform a strict no-op for every normal
    // message, so the 495 working modules are untouched.
    let mut global_enum_counts: std::collections::HashMap<String, usize> = Default::default();
    for line in body.lines() {
        if let Some(rest) = line.trim_start().strip_prefix("pub enum ") {
            if let Some(name) = rest.split_whitespace().next() {
                *global_enum_counts
                    .entry(name.trim_end_matches('{').trim().to_string())
                    .or_insert(0) += 1;
            }
        }
    }
    let dup_enums: std::collections::HashSet<String> = global_enum_counts
        .into_iter()
        .filter(|(_, c)| *c >= 2)
        .map(|(n, _)| n)
        .collect();
    if dup_enums.is_empty() {
        return body.to_string();
    }

    let lines: Vec<String> = body.lines().map(|l| l.to_string()).collect();
    let mut out: Vec<String> = Vec::with_capacity(lines.len());
    // counters keyed by name, reset on entering a struct / module
    let mut field_counts: std::collections::HashMap<String, usize> = Default::default();
    let mut enum_counts: std::collections::HashMap<String, usize> = Default::default();
    // when renaming an enum block, the whole-word substitution to apply until the
    // block ends (next `pub ` item at the submodule body indent, or dedent).
    let mut active_enum: Option<(String, String)> = None;

    for raw in &lines {
        let line = raw.clone();
        let trimmed = line.trim_start();

        // Reset scope counters at the start of a struct or module.
        if trimmed.starts_with("pub struct ") && line.trim_end().ends_with('{') {
            field_counts.clear();
        }
        if trimmed.starts_with("pub mod ") {
            enum_counts.clear();
            active_enum = None;
        }

        // --- enum definitions inside submodules ---
        if let Some(rest) = trimmed.strip_prefix("pub enum ") {
            active_enum = None;
            if let Some(name) = rest.split_whitespace().next() {
                let name = name.trim_end_matches('{').trim().to_string();
                if dup_enums.contains(&name) {
                    let n = enum_counts.entry(name.clone()).or_insert(0);
                    *n += 1;
                    if *n >= 2 {
                        active_enum = Some((name.clone(), format!("{name}{n}")));
                    }
                }
            }
        } else if trimmed.starts_with("pub enum ")
            || trimmed.starts_with("pub struct ")
            || trimmed.starts_with("pub mod ")
        {
            active_enum = None;
        }
        // Clear the active enum rename once we reach the next top-level item.
        if active_enum.is_some()
            && (trimmed.starts_with("pub mod ") || trimmed.starts_with("pub struct "))
        {
            active_enum = None;
        }

        if let Some((old, new)) = &active_enum {
            out.push(replace_word(&line, old, new));
            continue;
        }

        // --- struct field disambiguation ---
        // A field line looks like: `    pub <fname>: <Mod>::<Enum>,`
        if let Some(field) = parse_choice_field(trimmed)
            .filter(|f| dup_enums.contains(f.ty.rsplit("::").next().unwrap_or("")))
        {
            let n = field_counts.entry(field.name.clone()).or_insert(0);
            *n += 1;
            // Rewrite the preceding `#[yaserde(rename = "…")]` to flatten.
            if let Some(prev) = out.last_mut() {
                if prev.trim_start().starts_with("#[yaserde(rename") {
                    let indent: String =
                        prev.chars().take_while(|c| c.is_whitespace()).collect();
                    *prev = format!("{indent}#[yaserde(flatten)]");
                }
            }
            let indent: String = line.chars().take_while(|c| c.is_whitespace()).collect();
            if *n >= 2 {
                out.push(format!(
                    "{indent}pub {}_{n}: {}{n},",
                    field.name, field.ty
                ));
            } else {
                out.push(line);
            }
            continue;
        }

        out.push(line);
    }
    out.join("\n") + "\n"
}

struct ChoiceField {
    name: String,
    /// Full type path, e.g. `charge_15::Charge15Choice`.
    ty: String,
}

/// Parse a `pub <name>: <Mod>::<Enum>,` field that targets a `*Choice` enum in a
/// submodule (the inline-choice shape). Returns `None` otherwise.
fn parse_choice_field(trimmed: &str) -> Option<ChoiceField> {
    let rest = trimmed.strip_prefix("pub ")?;
    let (name, ty) = rest.split_once(": ")?;
    let ty = ty.trim_end_matches(',').trim();
    // Only the inline-choice fields: type is `mod::SomethingChoice` (has a path
    // and ends in "Choice").
    if ty.contains("::") && ty.ends_with("Choice") && !name.contains(' ') {
        Some(ChoiceField {
            name: name.to_string(),
            ty: ty.to_string(),
        })
    } else {
        None
    }
}

/// Replace whole-word occurrences of `old` with `new` (ASCII identifier chars).
fn replace_word(line: &str, old: &str, new: &str) -> String {
    let bytes = line.as_bytes();
    let mut result = String::with_capacity(line.len());
    let mut i = 0;
    while i < line.len() {
        if line[i..].starts_with(old) {
            let before_ok = i == 0 || !is_ident_byte(bytes[i - 1]);
            let after = i + old.len();
            let after_ok = after >= line.len() || !is_ident_byte(bytes[after]);
            if before_ok && after_ok {
                result.push_str(new);
                i = after;
                continue;
            }
        }
        let ch = line[i..].chars().next().unwrap();
        result.push(ch);
        i += ch.len_utf8();
    }
    result
}

fn is_ident_byte(b: u8) -> bool {
    b == b'_' || b.is_ascii_alphanumeric()
}

/// Names of complexTypes defined with `<xs:simpleContent>` (a text value plus
/// attributes), e.g. the ISO `…Amount` types. `xsd-parser` models only the
/// attributes and drops the text value, so we recover it.
fn simple_content_types(xsd: &str) -> std::collections::HashSet<String> {
    let mut set = std::collections::HashSet::new();
    let mut starts: Vec<usize> = Vec::new();
    for marker in ["<xs:complexType", "<xsd:complexType", "<complexType"] {
        let mut from = 0;
        while let Some(p) = xsd[from..].find(marker) {
            starts.push(from + p);
            from += p + marker.len();
        }
    }
    starts.sort_unstable();
    for (i, &st) in starts.iter().enumerate() {
        let end = starts.get(i + 1).copied().unwrap_or(xsd.len());
        let chunk = &xsd[st..end];
        if !chunk.contains("simpleContent") {
            continue;
        }
        // The complexType's own name is the first name="…" in the chunk.
        if let Some(np) = chunk.find("name=\"") {
            let after = &chunk[np + 6..];
            if let Some(q) = after.find('"') {
                set.insert(after[..q].to_string());
            }
        }
    }
    set
}

/// Inject a `#[yaserde(text)] pub value: String` field into each generated
/// struct that corresponds to a `simpleContent` complexType, so the text value
/// (e.g. a monetary amount) survives parse and serialize. The value is exposed
/// as a `String` to preserve the exact decimal representation (no float
/// rounding) and because yaserde only serializes `text` for string types.
fn add_simple_content_values(body: &str, names: &std::collections::HashSet<String>) -> String {
    let mut out = body.to_string();
    for name in names {
        let header = format!("pub struct {name} {{\n");
        if let Some(pos) = out.find(&header) {
            let insert_at = pos + header.len();
            let field = "    #[yaserde(text)]\n    pub value: String,\n";
            out.insert_str(insert_at, field);
        }
    }
    out
}

/// `xsd-parser` emits `#[yaserde(namespace = "urn:…")]` with no prefix. yaserde
/// 0.7 only builds a namespace-match arm when the type declares a prefix, so
/// that form makes deserialization reject every namespace ("bad namespace").
///
/// The working idiom for a default (unprefixed) namespace is
/// `prefix = "n", default_namespace = "n", namespace = "n: urn:…"`: the prefix
/// drives the deserialize match, while `default_namespace == prefix` makes
/// serialization still emit it as the default namespace (`xmlns="urn:…"`).
///
/// Attributes that already carry a prefix (`namespace = "p: urn:…"`) are left
/// untouched.
fn fix_namespaces(body: &str) -> String {
    let needle = "#[yaserde(namespace = \"";
    let mut out = String::with_capacity(body.len());
    let mut rest = body;
    while let Some(pos) = rest.find(needle) {
        out.push_str(&rest[..pos]);
        let after = &rest[pos + needle.len()..];
        let end = match after.find("\")]") {
            Some(e) => e,
            None => {
                // Malformed; emit as-is and stop transforming.
                out.push_str(&rest[pos..]);
                return out;
            }
        };
        let uri = &after[..end];
        // Skip values that already declare a prefix ("p: urn:…").
        if uri.contains(": ") {
            out.push_str(&rest[pos..pos + needle.len() + end + 3]);
        } else {
            out.push_str(&format!(
                "#[yaserde(prefix = \"n\", default_namespace = \"n\", namespace = \"n: {uri}\")]"
            ));
        }
        rest = &after[end + 3..];
    }
    out.push_str(rest);
    out
}

/// Some ISO 20022 schemas reach the same complex type via two element paths,
/// which makes `xsd-parser` emit byte-identical type definitions (and their
/// `impl` blocks) twice in one file, e.g. `Charge15Choice` in reda.001.001.04.
/// Rust rejects the redefinition. Because the repeated blocks are identical, we
/// can safely drop later exact duplicates of any top-level item.
///
/// We segment the body into top-level items by tracking `{}` nesting depth
/// (ISO 20022 namespaces never contain braces, so naive counting is safe here)
/// and keep the first occurrence of each distinct item text.
fn dedup_items(body: &str) -> String {
    let mut out = String::with_capacity(body.len());
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut chunk = String::new();
    let mut depth: i32 = 0;
    let flush = |chunk: &mut String, out: &mut String, seen: &mut std::collections::HashSet<String>| {
        let key = chunk.trim();
        if !key.is_empty() && seen.insert(key.to_string()) {
            out.push_str(chunk);
        }
        chunk.clear();
    };
    for line in body.lines() {
        chunk.push_str(line);
        chunk.push('\n');
        depth += line.matches('{').count() as i32 - line.matches('}').count() as i32;
        let trimmed = line.trim_end();
        // A top-level item ends when we are back at depth 0 and the line closes a
        // block (`}`) or a statement (`;`). Leading `#[..]`/comment/blank lines
        // accumulate into the next item.
        if depth <= 0 && (trimmed.ends_with('}') || trimmed.ends_with(';')) {
            depth = 0;
            flush(&mut chunk, &mut out, &mut seen);
        }
    }
    flush(&mut chunk, &mut out, &mut seen);
    out
}

/// Build the `impl crate::MxMessage for Document { … }` block giving the
/// message its ISO 20022 identity. Returns `""` if the file has no root
/// `Document` struct (so the caller skips identity for it).
fn mx_message_impl(family: &str, message_name: &str, namespace: &str, body: &str) -> String {
    if !body.contains("pub struct Document ") && !body.contains("pub struct Document\n") {
        return String::new();
    }
    let parts: Vec<&str> = message_name.split('.').collect();
    let (func, var, ver) = (parts[1], parts[2], parts[3]);
    format!(
        "\nimpl crate::MxMessage for Document {{\n\
         \x20   const BUSINESS_AREA: crate::BusinessArea = crate::BusinessArea::{family};\n\
         \x20   const FUNCTIONALITY: &'static str = {func:?};\n\
         \x20   const VARIANT: &'static str = {var:?};\n\
         \x20   const VERSION: &'static str = {ver:?};\n\
         \x20   const MESSAGE_NAME: &'static str = {message_name:?};\n\
         \x20   const NAMESPACE: &'static str = {namespace:?};\n\
         }}\n"
    )
}

/// Turn a module stem into an enum variant identifier, e.g.
/// `pacs_008_001_08` -> `Pacs_008_001_08`.
fn variant_ident(stem: &str) -> String {
    let mut c = stem.chars();
    match c.next() {
        Some(first) => first.to_ascii_uppercase().to_string() + c.as_str(),
        None => stem.to_string(),
    }
}

/// Emit `src/generated/any.rs`: the `AnyMessage` dispatch enum and `parse_auto`,
/// the rust parallel to prowide's `AbstractMX.parse(xml)` auto-detection.
fn write_any(output: &Path, msgs: &[(String, String, String)]) {
    let mut sorted = msgs.to_vec();
    sorted.sort();
    let mut s = String::from(
        "// @generated by src/bin/codegen.rs. Do not edit.\n\
         #![allow(non_camel_case_types)]\n\
         //! Auto-detecting message dispatch over every generated message.\n\n\
         use crate::MxMessage;\n\n\
         /// Parse into a boxed `T`. Keeping each (potentially very large) message\n\
         /// construction in its own monomorphized frame stops `parse_auto`'s frame\n\
         /// from having to reserve space for the largest message across all arms.\n\
         #[inline(never)]\n\
         fn parse_boxed<T: ::yaserde::YaDeserialize>(xml: &str) -> crate::Result<Box<T>> {\n\
         \x20   Ok(Box::new(crate::from_xml::<T>(xml)?))\n\
         }\n\n\
         /// One variant per generated ISO 20022 message version.\n\
         pub enum AnyMessage {\n",
    );
    for (family, stem, _) in &sorted {
        let v = variant_ident(stem);
        s.push_str(&format!(
            "    #[cfg(feature = \"model-{family}\")]\n    {v}(Box<crate::generated::{family}::{stem}::Document>),\n"
        ));
    }
    s.push_str("}\n\nimpl AnyMessage {\n");
    // message_name()
    s.push_str("    /// The canonical message name of the contained message.\n    pub fn message_name(&self) -> &'static str {\n        match self {\n");
    for (family, stem, _) in &sorted {
        let v = variant_ident(stem);
        s.push_str(&format!(
            "            #[cfg(feature = \"model-{family}\")]\n            AnyMessage::{v}(_) => <crate::generated::{family}::{stem}::Document as MxMessage>::MESSAGE_NAME,\n"
        ));
    }
    s.push_str("        }\n    }\n\n");
    // mx_id()
    s.push_str("    /// The identification of the contained message.\n    pub fn mx_id(&self) -> crate::MxId {\n        match self {\n");
    for (family, stem, _) in &sorted {
        let v = variant_ident(stem);
        s.push_str(&format!(
            "            #[cfg(feature = \"model-{family}\")]\n            AnyMessage::{v}(_) => <crate::generated::{family}::{stem}::Document as MxMessage>::mx_id(),\n"
        ));
    }
    s.push_str("        }\n    }\n}\n\n");
    // parse_auto
    s.push_str(
        "/// Detect the message type from the XML namespace and parse it into the\n\
         /// matching [`AnyMessage`] variant. Mirrors prowide's `AbstractMX.parse`.\n\
         pub fn parse_auto(xml: &str) -> crate::Result<AnyMessage> {\n\
         \x20   let id = crate::detect(xml)\n\
         \x20       .ok_or_else(|| crate::Error::InvalidMxId(\"no ISO 20022 namespace found in XML\".to_string()))?;\n\
         \x20   match id.message_name().as_str() {\n",
    );
    for (family, stem, message_name) in &sorted {
        let v = variant_ident(stem);
        s.push_str(&format!(
            "        #[cfg(feature = \"model-{family}\")]\n        {message_name:?} => Ok(AnyMessage::{v}(parse_boxed::<crate::generated::{family}::{stem}::Document>(xml)?)),\n"
        ));
    }
    s.push_str(
        "        other => Err(crate::Error::InvalidMxId(format!(\n\
         \x20           \"no generated model for message {other}\"\n\
         \x20       ))),\n    }\n}\n",
    );
    fs::write(output.join("any.rs"), s).expect("write generated/any.rs");
}

fn main() {
    let args = parse_args();
    fs::create_dir_all(&args.output).expect("create output dir");

    let mut entries: Vec<PathBuf> = fs::read_dir(&args.input)
        .unwrap_or_else(|e| panic!("read input dir {:?}: {e}", args.input))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().map(|x| x == "xsd").unwrap_or(false))
        .collect();
    entries.sort();

    // family -> (module stem -> namespace) so we can emit per-family mod.rs files.
    let mut families: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    // Catalogue rows for every message: (message_name, namespace, family, has_model).
    let mut catalogue: Vec<(String, String, String, bool)> = Vec::new();
    // Generated messages for the AnyMessage dispatch enum: (family, stem, message_name).
    let mut generated_msgs: Vec<(String, String, String)> = Vec::new();
    let (mut ok, mut failed, mut skipped) = (0usize, 0usize, 0usize);

    for path in &entries {
        let basename = path.file_name().unwrap().to_string_lossy().to_string();
        if !args.only.is_empty() && !args.only.contains(&basename) {
            continue;
        }
        let Some((family, stem, message_name)) = message_stem(&basename) else {
            eprintln!("SKIP {basename} (non-canonical message name)");
            continue;
        };
        let xsd_text = fs::read_to_string(path).expect("read xsd");
        let namespace = extract_namespace(&xsd_text).unwrap_or_default();

        if !args.no_skip && SKIP.contains(&basename.as_str()) {
            eprintln!("SKIP {basename} (multiple anonymous choice groups)");
            skipped += 1;
            // Still catalogued, just without a generated model.
            catalogue.push((message_name, namespace, family, false));
            continue;
        }

        match generate_one(&xsd_text) {
            Ok(body) => {
                let family_dir = args.output.join(&family);
                fs::create_dir_all(&family_dir).expect("create family dir");
                let out = family_dir.join(format!("{stem}.rs"));
                let identity = mx_message_impl(&family, &message_name, &namespace, &body);
                let contents = format!("{HEADER}\n{body}{identity}");
                fs::write(&out, contents).expect("write generated file");
                families
                    .entry(family.clone())
                    .or_default()
                    .insert(stem.clone(), namespace.clone());
                if !identity.is_empty() {
                    generated_msgs.push((family.clone(), stem, message_name.clone()));
                }
                catalogue.push((message_name, namespace, family, true));
                ok += 1;
            }
            Err(e) => {
                failed += 1;
                eprintln!("FAIL {basename}: {e}");
            }
        }
    }

    write_mods(&args.output, &families, &generated_msgs);
    write_any(&args.output, &generated_msgs);
    write_catalogue(&catalogue);
    println!(
        "generated {ok} message modules ({skipped} skipped, {failed} failed), {} families, {} catalogue entries",
        families.len(),
        catalogue.len()
    );
}

/// Emit `src/catalogue/data.rs` with the `ENTRIES` slice and the `BY_NAME` phf map.
fn write_catalogue(rows: &[(String, String, String, bool)]) {
    let mut sorted = rows.to_vec();
    sorted.sort();
    let mut s = String::from(
        "// @generated by src/bin/codegen.rs. Do not edit.\nuse super::CatalogueEntry;\nuse phf::phf_map;\n\n",
    );
    s.push_str("pub static ENTRIES: &[CatalogueEntry] = &[\n");
    for (name, ns, family, has_model) in &sorted {
        s.push_str(&format!(
            "    CatalogueEntry {{ message_name: {name:?}, namespace: {ns:?}, business_area: {family:?}, has_model: {has_model} }},\n"
        ));
    }
    s.push_str("];\n\npub static BY_NAME: phf::Map<&'static str, CatalogueEntry> = phf_map! {\n");
    for (name, ns, family, has_model) in &sorted {
        s.push_str(&format!(
            "    {name:?} => CatalogueEntry {{ message_name: {name:?}, namespace: {ns:?}, business_area: {family:?}, has_model: {has_model} }},\n"
        ));
    }
    s.push_str("};\n");
    fs::write("src/catalogue/data.rs", s).expect("write catalogue data.rs");
}

/// Emit `src/generated/mod.rs` plus one `mod.rs` per family.
fn write_mods(
    output: &Path,
    families: &BTreeMap<String, BTreeMap<String, String>>,
    generated_msgs: &[(String, String, String)],
) {
    let mut root = String::from("// @generated by src/bin/codegen.rs. Do not edit.\n");
    for family in families.keys() {
        root.push_str(&format!(
            "#[cfg(feature = \"model-{family}\")]\npub mod {family};\n"
        ));
    }
    root.push_str("pub mod any;\n");
    fs::write(output.join("mod.rs"), root).expect("write generated/mod.rs");

    // Stems that have a root `Document` (so a smoke test can be generated).
    let mut has_doc: std::collections::HashSet<(String, String)> = std::collections::HashSet::new();
    for (family, stem, _) in generated_msgs {
        has_doc.insert((family.clone(), stem.clone()));
    }

    for (family, messages) in families {
        let mut m = String::from("// @generated by src/bin/codegen.rs. Do not edit.\n");
        for stem in messages.keys() {
            m.push_str(&format!("pub mod {stem};\n"));
        }
        // Structural smoke tests: every message type constructs and serializes.
        // (Re-parsing an all-empty `Default` is a degenerate case that some
        // messages legitimately reject, so we assert serialization only.)
        // Run on a large-stack thread because some messages are huge.
        let doc_stems: Vec<&String> = messages
            .keys()
            .filter(|s| has_doc.contains(&(family.clone(), (*s).clone())))
            .collect();
        if !doc_stems.is_empty() {
            m.push_str("\n#[cfg(test)]\nmod smoke {\n");
            for stem in doc_stems {
                m.push_str(&format!(
                    "    #[test]\n    fn {stem}() {{\n        \
                     ::std::thread::Builder::new().stack_size(64 << 20).spawn(|| {{\n            \
                     let d = super::{stem}::Document::default();\n            \
                     let xml = crate::to_xml(&d).expect(\"serialize\");\n            \
                     assert!(xml.contains(\"Document\"));\n        \
                     }}).unwrap().join().unwrap();\n    }}\n"
                ));
            }
            m.push_str("}\n");
        }
        fs::write(output.join(family).join("mod.rs"), m).expect("write family mod.rs");
    }
}
